flowchart TB
  A0["Tela de Logon"] --> A1["Console de Administração"]
  A1 --> A2["Manter Cartas"]
  A1 --> A3["Cadastros Básicos"]
  A1 --> A4["Manter Pacotes"]
  A1 --> A5["Manter Temporadas"]
  A1 --> A6["Segurança"]
  A1 --> A7["Operações"]

  A3 --> A3a["Raridade"]
  A3 --> A3b["Elemento"]
  A3 --> A3c["Expansão"]
  A3 --> A3d["Formato"]
  A3 --> A3e["Divisão"]
  A3 --> A3f["Status da Partida"]

  A6 --> A6a["Usuários"]
  A6 --> A6b["Perfis de Acesso"]
  A6 --> A6c["Funções do Sistema"]

  A7 --> A7a["Executar Backup"]
  A7 --> A7b["Restaurar Backup"]
  A7 --> A7c["Gerar Histórico"]
  A7 --> A7d["Log de Auditoria"]